version: '{branch}-{build}'
image: Visual Studio 2019

environment:
  NODE_ENV: production

install:
- ps: |-
    Install-Product node 8.11 x64

cache:
- source/WebApp/node_modules -> source/WebApp/package.json

build_script:
- cmd: sl ci

artifacts:
- path: ./Server.AspNetCore.zip
  name: Server.AspNetCore.zip
- path: ./Server.Owin.zip
  name: Server.Owin.zip
- path: ./WebApp.zip
  name: WebApp.zip

deploy:

- provider: AzureAppServiceZipDeploy
  website: sharplab-edge
  username: ashmind
  password:
    secure: FUzpPhO20JDsbK33tI4pWUiu2GJzkMRGPbFpXjXCOHMHAs39F0tPqb6v4qQzGTYix/mA2Qhee4wFcX4H8zSPeA==
  artifact: WebApp.zip
  on:
    branch: edge

- provider: AzureAppServiceZipDeploy
  website: sl-a-edge-core-x64
  username: ashmind
  password:
    secure: FUzpPhO20JDsbK33tI4pWUiu2GJzkMRGPbFpXjXCOHMHAs39F0tPqb6v4qQzGTYix/mA2Qhee4wFcX4H8zSPeA==
  artifact: Server.AspNetCore.zip
  on:
    branch: edge

- provider: AzureAppServiceZipDeploy
  website: sl-a-edge-core-x64-profiled
  username: ashmind
  password:
    secure: FUzpPhO20JDsbK33tI4pWUiu2GJzkMRGPbFpXjXCOHMHAs39F0tPqb6v4qQzGTYix/mA2Qhee4wFcX4H8zSPeA==
  artifact: Server.AspNetCore.zip
  on:
    branch: edge

- provider: AzureAppServiceZipDeploy
  website: sl-a-edge-netfx
  username: ashmind
  password:
    secure: FUzpPhO20JDsbK33tI4pWUiu2GJzkMRGPbFpXjXCOHMHAs39F0tPqb6v4qQzGTYix/mA2Qhee4wFcX4H8zSPeA==
  artifact: Server.Owin.zip
  on:
    branch: edge

- provider: AzureAppServiceZipDeploy
  website: sharplab
  username: ashmind
  password:
    secure: FUzpPhO20JDsbK33tI4pWUiu2GJzkMRGPbFpXjXCOHMHAs39F0tPqb6v4qQzGTYix/mA2Qhee4wFcX4H8zSPeA==
  artifact: WebApp.zip
  on:
    branch: master

- provider: AzureAppServiceZipDeploy
  website: sl-a-core-x64
  username: ashmind
  password:
    secure: FUzpPhO20JDsbK33tI4pWUiu2GJzkMRGPbFpXjXCOHMHAs39F0tPqb6v4qQzGTYix/mA2Qhee4wFcX4H8zSPeA==
  artifact: Server.AspNetCore.zip
  on:
    branch: master

- provider: AzureAppServiceZipDeploy
  website: sl-a-core-x64-profiled
  username: ashmind
  password:
    secure: FUzpPhO20JDsbK33tI4pWUiu2GJzkMRGPbFpXjXCOHMHAs39F0tPqb6v4qQzGTYix/mA2Qhee4wFcX4H8zSPeA==
  artifact: Server.AspNetCore.zip
  on:
    branch: master

- provider: AzureAppServiceZipDeploy
  website: sl-a-x64
  username: ashmind
  password:
    secure: FUzpPhO20JDsbK33tI4pWUiu2GJzkMRGPbFpXjXCOHMHAs39F0tPqb6v4qQzGTYix/mA2Qhee4wFcX4H8zSPeA==
  artifact: Server.Owin.zip
  on:
    branch: master

- provider: AzureAppServiceZipDeploy
  website: sl-a-netfx
  username: ashmind
  password:
    secure: FUzpPhO20JDsbK33tI4pWUiu2GJzkMRGPbFpXjXCOHMHAs39F0tPqb6v4qQzGTYix/mA2Qhee4wFcX4H8zSPeA==
  artifact: Server.Owin.zip
  on:
    branch: master